language: c

compiler:
  - clang
  - gcc

before_install: sudo apt-get update -qq

install: sudo apt-get install -qq --no-install-recommends asciidoc xmlto docbook-utils valgrind

script:
  - # ============ Build from config ===============
  - cp contrib/config.make .
  - make DESTDIR=/tmp/bare-prefix all-debug install install-doc
  - make test
  - make test TEST_OPTS=valgrind
  - make distclean
  - # ============ Build using autoconf ============
  - make dist
  - ./configure --prefix=/tmp/conf-prefix
  - make V=1 TEST_SHELL=bash all test install install-doc
  - make clean
