language: c

# LeakSanitizer requires ptrace capabilities
# https://github.com/travis-ci/travis-ci/issues/9033
sudo: required

addons:
  apt:
    packages:
    - asciidoc
    - xmlto
    - valgrind

env:
  global:
  matrix:
    - TRAVIS_TIG=autoconf
    - TRAVIS_TIG=config

compiler:
  - gcc
  - clang

script: tools/travis.sh

matrix:
  include:
  - if: branch = master
    os: osx
    env:
    compiler: clang
    script: brew install --HEAD tig
  - if: branch = master
    os: osx
    env:
    compiler: gcc
    script: brew install --HEAD tig
